// packages/word-finder-ui-vue/src/app/WordResult.vue
<template>
    <div class="results">
        <p>String '<span class="string">{{formResult.word.textString}}</span>'
            <span v-if="formResult.word.existsInDictionary">exists</span>
            <span v-else>does not exist</span>
            in {{formResult.selectedLanguage}} dictionary.
        </p>
        <p v-if="wordHasAnagrams()"> Anagrams: {{anagrams()}}</p>
        <p v-else>No anagrams found.</p>
    </div>
</template>

<script lang="ts">
    import {Component, Prop, Vue} from "vue-property-decorator";
    import {Result} from "./result";

    @Component
    export default class WordResult extends Vue {
        @Prop() private formResult!: Result;

        anagrams(): string {
            return this.formResult.word.dictionaryAnagrams.join(', ');
        }

        wordHasAnagrams(): boolean {
            return this.formResult.word.dictionaryAnagrams?.length > 0;
        }
    }
</script>

// packages/word-finder-ui-ng/src/app/word/result/word-result.component.ts
import {Component, Input} from '@angular/core';
import {Result} from '../form/word-form.component';

@Component({
  selector: 'app-word-result',
  templateUrl: './word-result.component.html'
})
export class WordResultComponent {

  @Input()
  formResult: Result;

  formattedAnagrams() {
    return this.formResult.word.dictionaryAnagrams
      .map(s => ' ' + s);
  }

  wordHasAnagrams(): boolean {
    return this.formResult.word.dictionaryAnagrams?.length > 0;
  }
}

<div class="results">
  <p>String '<span class="string">{{formResult?.word?.textString}}</span>'
    <span *ngIf="formResult?.word?.existsInDictionary; else notExists">exists</span>
    <ng-template #notExists>does not exist</ng-template>
    in {{formResult.selectedLanguage}} dictionary.
  </p>
  <p *ngIf="wordHasAnagrams(); else noAnagrams">Anagrams: {{formattedAnagrams()}}</p>
  <ng-template #noAnagrams>No anagrams found.</ng-template>
</div>
